/**
 * Renders a unified patch string (red/green line-based). No diff library —
 * the patch is already generated by the store reducer (`unifiedPatch`).
 */
export default function DiffBlock({
  path,
  patch,
}: {
  path: string;
  patch: string;
}) {
  const lines = patch.split("\n");

  return (
    <div className="overflow-hidden rounded-md bg-surface">
      <div className="border-b border-border px-3 py-1.5 font-mono text-ui-sm text-foreground-subtle">
        {path}
      </div>
      <pre className="overflow-x-auto p-2 font-mono text-sm leading-5">
        {lines.map((line, i) => {
          let cls = "text-foreground-subtle";
          if (line.startsWith("+") && !line.startsWith("+++")) {
            cls = "text-diff-added";
          } else if (line.startsWith("-") && !line.startsWith("---")) {
            cls = "text-diff-removed";
          } else if (line.startsWith("@@")) {
            cls = "text-icon-blue";
          }
          return (
            <div key={i} className={cls}>
              {line === "" ? " " : line}
            </div>
          );
        })}
      </pre>
    </div>
  );
}
