/**
 * Renders a unified patch string (red/green line-based). No diff library —
 * the patch is already generated by the store reducer (`unifiedPatch`).
 */
export default function DiffBlock({
  path,
  patch,
}: {
  path: string;
  patch: string;
}) {
  const lines = patch.split("\n");

  return (
    <div className="overflow-hidden rounded-md border border-neutral-700 bg-neutral-900 text-xs">
      <div className="border-b border-neutral-700 bg-neutral-800 px-3 py-1.5 font-mono text-neutral-300">
        {path}
      </div>
      <pre className="overflow-x-auto p-2 font-mono leading-5">
        {lines.map((line, i) => {
          let cls = "text-neutral-400";
          if (line.startsWith("+") && !line.startsWith("+++")) {
            cls = "bg-green-900/40 text-green-300";
          } else if (line.startsWith("-") && !line.startsWith("---")) {
            cls = "bg-red-900/40 text-red-300";
          } else if (line.startsWith("@@")) {
            cls = "text-sky-300";
          }
          return (
            <div key={i} className={cls}>
              {line === "" ? " " : line}
            </div>
          );
        })}
      </pre>
    </div>
  );
}
